name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose -y

      - name: Build and run services
        run: make db

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..30}; do
            nc -zv localhost 27017 && echo "MongoDB is up" && break
            echo "Waiting for MongoDB..."
            sleep 2
          done

      - name: Run tests
        run: make tests

      - name: Clean up
        run: make db-down
